name: "Check Nix flake"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: "Build Nix targets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mount Nix store
        run: |
          sudo install -d -o "$USER" /nix
          sudo install -d -o "$USER" /mnt/nixroot
          sudo mount --bind /mnt/nixroot /nix
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
      - name: Build all NixOS configurations
        run: "nix flake show --json | jq -r '.nixosConfigurations | keys[]' | xargs -I {} nix build -vvvvv --accept-flake-config --no-link .#nixosConfigurations.{}.config.system.build.toplevel"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.NIX_CACHE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NIX_CACHE_SECRET_ACCESS_KEY }}
