name: "Check Nix flake"

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: "Build Nix targets"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            auto-optimise-store = true
            min-free = 1000000000
            max-free = 2000000000
      - name: Build all NixOS configurations
        run: |
          sudo install -d -o "$USER" /mnt/nixroot
          nix flake show --json | jq -r '.nixosConfigurations | keys[]' | xargs -I {} nix build --store /mnt/nixroot --no-link .#nixosConfigurations.{}.config.system.build.toplevel
